server:
  port: 0

spring:
  application:
    name: catalog-service
  datasource:
    url: "jdbc:mysql://localhost:3306/sample2?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC"
    username: root
    password: 'you need put on environment variable `SPRING_DATASOURCE_PASSWORD`'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      minimum-idle: 10
      maximum-pool-size: 40
      connection-timeout: 30000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
