server:
  port: 8000

spring:
  application:
    name: gateway-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - CustomFilter
            - RewritePath=/users/actuator/(?<segment>.*), /actuator/$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - CustomFilter
            - RewritePath=/users/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
            - Method=GET
          filters:
            - AuthorizationHeaderFilter
            - CustomFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - CustomFilter
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/actuator/**
            - Method=GET,POST
          filters:
            - RewritePath=/order-service/actuator/(?<segment>.*), /actuator/$\{segment}
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - CustomFilter
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalogs/**
          filters:
            - CustomFilter
        - id: first-service
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/first-service/**
          filters:
            - AddRequestHeader=First-Request-Id, header2
            - AddResponseHeader=First-Response, response2
            - CustomFilter
        - id: second-service
          uri: lb://MY-SECOND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            - AddRequestHeader=Second-Request-Id, header2
            - AddResponseHeader=Second-Response, response2
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: HELLO, Spring Cloud Gateway LoggingFilter
                preLogger: true
                postLogger: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, refresh, beans, info, httptrace, busrefresh, busenv, prometheus, metrics
